sudo: false
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install -r requirements.txt
  - pip install pytest pytest_cov codecov

script:
  - python -m pytest --cov=numerapi
  - flake8 numerapi

after_success:
  - codecov
